baseURL: https://pasztor.at
disablePathToLower: false
languageCode: en-us
title: Janos Pasztor
theme: pasztor.at
copyright: <span role="text" aria-label="Copyright Yanosh Pastor. All rights reserved.">Copyright &copy; Janos Pasztor. All rights reserved.</span>
disableHugoGeneratorInject: true
enableGitInfo: true
author:
  - Janos Pasztor
permalinks:
  blog: /blog/:slug/
taxonomies:
  tag: tags
  author: authors
params:
  title: Janos Pasztor
  images:
    - social.png
  description: Random thoughts from a software engineer with 10+ years of experience.
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: monokai
    tabWidth: 4
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: -110
    - identifier: blog
      name: Blog
      url: /blog/
      weight: -100
    - identifier: podcast
      name: Podcast
      url: /podcast/
      weight: -90
    - identifier: about
      name: About me
      url: /about/
      weight: -80
    - identifier: discord
      name: Join my Discord
      url: https://discord.gg/sEWQcpe
      weight: -70
  footer:
    - identifier: social
      name: Social
      weight: 2
    - identifier: social-linkedin
      parent: social
      name: LinkedIn
      url: https://www.linkedin.com/in/janoszen
      weight: 1
    - identifier: social-github
      parent: social
      name: GitHub
      url: https://github.com/janoszen
      weight: 2
    - identifier: social-twitter
      parent: social
      name: Twitter
      url: https://twitter.com/janoszen
      weight: 3
    - identifier: social-discord
      parent: social
      name: Discord
      url: /discord
      weight: 4
    - identifier: social-rss
      parent: social
      name: RSS
      url: /feed.xml
      weight: 5

    - identifier: podcast
      name: Podcast
      weight: 4
    - identifier: podcast-spotify
      parent: podcast
      name: Spotify
      url: https://open.spotify.com/show/7CIjRONYPExPeFs2R8GDZ0
      weight: 1
    - identifier: podcast-itunes
      parent: podcast
      name: iTunes
      url: https://podcasts.apple.com/podcast/janos-pasztor/id1524971396
      weight: 2
    - identifier: podcast-soundcloud
      parent: podcast
      name: SoundCloud
      url: https://soundcloud.com/pasztor_at/
      weight: 3
    - identifier: podcast-deezer
      parent: podcast
      name: Deezer
      url: https://deezer.com/show/1564152
      weight: 4
    - identifier: podcast-rss
      parent: podcast
      name: RSS
      url: /podcast.xml
      weight: 5

    - identifier: legal
      name: Legal
      weight: 5
    - identifier: imprint
      parent: legal
      name: Imprint
      url: /imprint/
      weight: 1
    - identifier: privacy
      parent: legal
      name: Privacy
      url: /privacy/
      weight: 2
    - identifier: terms
      parent: legal
      name: Terms
      url: /terms/
      weight: 3

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
outputFormats:
  Podcast:
    baseName: podcast
    rel: alternate
    isPlainText: false
    isHTML: false
    noUgly: true
    permalinkable: false
    mediaType:
      delimiter: .
      mainType: application
      string: application/rss+xml
      subType: rss
      suffixes:
        - xml
      type: application/rss+xml
  feed:
    baseName: feed
    rel: alternate
    isPlainText: false
    isHTML: false
    noUgly: true
    permalinkable: false
    mediaType:
      delimiter: .
      mainType: application
      string: application/rss+xml
      subType: rss
      suffixes:
        - xml
      type: application/rss+xml
outputs:
  home:
    - HTML
    - Podcast
    - feed
disableKinds:
  - taxonomyTerm
