baseURL: https://pasztor.at
disablePathToLower: true
languageCode: en-us
title: Janos Pasztor
theme: pasztor.at
copyright: Copyright © Janos Pasztor. All rights reserved.
permalinks:
  blog: /blog/:slug/
  author: /about/:slug/
taxonomies:
  tag: tags
  author: authors
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: monokai
    tabWidth: 4
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: -110
    - identifier: blog
      name: Blog
      url: /blog/
      weight: -100
    - identifier: about
      name: About Us
      url: /about/
      weight: -90
    - identifier: discord
      name: Join our Discord
      url: https://discord.gg/sEWQcpe
      weight: -80
  footer:
    - identifier: about
      name: About Us
      weight: 1
    - identifier: about-sanja
      parent: about
      name: Sanja
      url: /about/sanja
      weight: 1
    - identifier: about-janos
      parent: about
      name: Janos
      url: /about/janos
      weight: 2

    - identifier: subscribe
      name: Subscribe
      weight: 2
    - identifier: subscribe-discord
      parent: subscribe
      name: Discord
      url: /discord
      weight: 1
    - identifier: subscribe-rss
      parent: subscribe
      name: RSS
      url: /rss.xml
      weight: 2

    - identifier: legal
      name: Legal
      weight: 3
    - identifier: imprint
      parent: legal
      name: Imprint
      url: /imprint/
      weight: 1
    - identifier: privacy
      parent: legal
      name: Privacy
      url: /privacy/
      weight: 2
    - identifier: terms
      parent: legal
      name: Terms
      url: /terms/
      weight: 3

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
outputFormats:
  Podcast:
    baseName: podcast
    rel: alternate
    isPlainText: false
    isHTML: false
    noUgly: true
    permalinkable: false
    mediaType:
      delimiter: .
      mainType: application
      string: application/rss+xml
      subType: rss
      suffixes:
        - xml
      type: application/rss+xml
outputs:
  home:
    - HTML
    - Podcast
