baseURL: https://pasztor.at
disablePathToLower: true
languageCode: en-us
title: Sanja & Janos
theme: pasztor.at
copyright: Copyright © Janos Pasztor. All rights reserved.
permalinks:
  blog: /blog/:slug/
markup:
  goldmark:
    renderer:
      unsafe: true
taxonomies:
  blog: blog
  about: about
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: -110
    - identifier: blog
      name: Blog
      url: /blog/
      weight: -100
    - identifier: about
      name: About Us
      url: /about/
      weight: -90
  footer:
    - identifier: about
      name: About Us
    - identifier: about-janos
      parent: about
      name: Janos
      url: /about/janos
    - identifier: about-sanja
      parent: about
      name: Sanja
      url: /about/sanja
    - identifier: legal
      name: Legal
    - identifier: imprint
      parent: legal
      name: Imprint
      url: /imprint/
    - identifier: privacy
      parent: legal
      name: Privacy Policy
      url: /privacy/
    - identifier: terms
      parent: legal
      name: Terms of Use
      url: /terms/

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5