baseURL: https://pasztor.at
disablePathToLower: false
languageCode: en-us
title: Janos & Sanja
theme: pasztor.at
copyright: <span role="text" aria-label="Copyright Yanosh Pastor and Sanya Bonitch. All rights reserved.">Copyright &copy; Janos Pasztor &amp; Sanja Bonic. All rights reserved.</span><br />Do not copy. <a href="/terms">Click here for acceptable use.</a>
disableHugoGeneratorInject: true
enableGitInfo: true
author:
  - Janos Pasztor
  - Sanja Bonic
permalinks:
  blog: /blog/:slug/
taxonomies:
  tag: tags
  category: categories
  author: authors
params:
  title: Janos & Sanja
  copyright: Copyright &copy; Janos Pasztor &amp; Sanja Bonic. All rights reserved. Do not copy.
  images:
    - social.png
  description: Random thoughts from a Software Engineer and a Software Engineering Manager.
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: monokai
    tabWidth: 4
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: -110
    - identifier: technology
      name: Technology
      url: /categories/technology/
      weight: -100
    - identifier: podcast
      name: Podcast
      url: /podcast/
      weight: -90
    - identifier: about
      name: About us
      url: /about/
      weight: -80
    - identifier: discord
      name: Join our Discord
      url: https://discord.gg/sEWQcpe
      weight: -70
  footer:
    - identifier: janos
      name: Janos
      weight: 1
    - identifier: janos-linkedin
      parent: janos
      name: LinkedIn
      url: https://www.linkedin.com/in/janoszen
      weight: 1
    - identifier: janos-github
      parent: janos
      name: GitHub
      url: https://github.com/janoszen
      weight: 2
    - identifier: janos-twitter
      parent: janos
      name: Twitter
      url: https://twitter.com/janoszen
      weight: 3

    - identifier: sanja
      name: Sanja
      weight: 2
    - identifier: sanja-linkedin
      parent: sanja
      name: LinkedIn
      url: https://www.linkedin.com/in/sanjabonic
      weight: 1
    - identifier: sanja-github
      parent: sanja
      name: GitHub
      url: https://github.com/sanjabonic
      weight: 2

    - identifier: social
      name: Social
      weight: 3
    - identifier: social-discord
      parent: social
      name: Discord
      url: /discord
      weight: 1
    - identifier: social-rss
      parent: social
      name: RSS (all)
      url: /rss.xml
      weight: 2
    - identifier: social-rss-tech
      parent: social
      name: RSS (tech)
      url: /technology.xml
      weight: 3

    - identifier: legal
      name: Legal
      weight: 5
    - identifier: imprint
      parent: legal
      name: Imprint
      url: /imprint/
      weight: 1
    - identifier: privacy
      parent: legal
      name: Privacy
      url: /privacy/
      weight: 2
    - identifier: terms
      parent: legal
      name: Terms
      url: /terms/
      weight: 3

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
mediaTypes:
  text/netlify:
    suffixes: [""]
    delimiter: ""
outputFormats:
  Podcast:
    name: Podcast
    baseName: podcast
    rel: alternate
    isPlainText: false
    isHTML: false
    noUgly: true
    permalinkable: false
    mediaType:
      delimiter: .
      mainType: application
      string: application/rss+xml
      subType: rss
      suffixes:
        - xml
      type: application/rss+xml
  rss:
    name: RSS
    baseName: rss
    rel: alternate
    isPlainText: false
    isHTML: false
    noUgly: true
    permalinkable: false
    mediaType:
      delimiter: .
      mainType: application
      string: application/rss+xml
      subType: rss
      suffixes:
        - xml
      type: application/rss+xml
  technology:
    name: Technology
    baseName: technology
    rel: alternate
    isPlainText: false
    isHTML: false
    noUgly: true
    permalinkable: false
    mediaType:
      delimiter: .
      mainType: application
      string: application/rss+xml
      subType: rss
      suffixes:
        - xml
      type: application/rss+xml
  headers:
    mediatype: text/netlify
    baseName: _headers
    isPlainText: true
    notAlternative: true
outputs:
  home:
    - HTML
    - Podcast
    - Technology
    - RSS
    - headers
disableKinds:
  - taxonomyTerm
